name: Linux riscv64
on:
  push
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "~/.m2:/root/.m2" --volume "${PWD}:/mnt"
          install: |
            apt-get update
            apt-get -y install openjdk-11-jdk-headless git curl wget gzip
            wget https://raw.githubusercontent.com/jjlauer/provisioning/master/linux/bootstrap-maven.sh
            chmod +x ./bootstrap-maven.sh
            ./bootstrap-maven.sh
          run: |
            export PATH=$PATH:/opt/maven/current/bin
            cd /mnt
            mvn test